language: java
jdk:
  - oraclejdk8
branches:
  only:
  - master
env:
  global:
    - secure: "k3oYYnSpE4iDCnpaELQZLnSPn7AVm5VlSGm356SmPEKDKnS12rdNnmK5X4P5CdGhSmttsSJKbLHP+/C8vreEJQiePRqZ7pbq65SvnPSFmQpLIA2KOe/eV5cFPZDDvNZoijWPYqxGIfbBLZDiL8VTVVz9JYDrhaTMLgKxU7jrMj3qaH1C8rMjqSwW7JN00g0Nq5SVXZv9Hu3Aqd1DUD5GgY4ts4kRUXz31wGwuNVnYMAlydlJCPpjW55oS8WDj7kl+BoEU8CU2ZdFq49CDGeiHZOpJGT57Ggj7ZJUOigoj7Vsl47bpwJcucSGPjDrm6tOOMeRvphFf6291f6aPLXTcB5nzgn/xTGuC7pCc/gKUMSQtnBzkwclutvxiaAR0rzsBs0GcV/WMva31grsIWxFXuPeRgB3GcMuae8qmhLDsq2Lp6ez45JKJtlvms1P0T0ao9xbSMfVVnagC1XNOE7ieBJoUl4yF2nUmC4lCdNTGDY4J61Kqfet/U3ii33vX4mPb2i6SJAXtSzLPr8mwq+5kpBZxeQPI0QUg7+7rmelz5wBOGDtkax1o969OLjaVhuVTkNjsYRszqbM5eMMlpoNT4DU5F5kJSLWEIx7H4nXERgPQqWMDrb6j0g3eV+pzz4qyn3w2auCkXX5g6TG8RhmgUMv76iPrl7XpbKhj6sjBI8="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "wultra/powerauth-cmd-tool"
      description: "Build submitted via Travis CI"
    notification_email: roman.strobl@wultra.com
    build_command_prepend: "mvn clean"
    build_command: "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan
